name: Pulumi
on:
  push:
    branches:
      - main
env:
  AWS_REGION : "us-west-2"   
permissions:
  id-token: write
  contents: read
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: github-actions-session
          aws-region: ${{ env.AWS_REGION }}
      - run: npm install
      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: team-ce/lotctl
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}